name: Data Dictionary Checks

on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Create a copy of the updated data-dictonary file
      - name: Make a copy of file_1.json
        run: cp file_1.json file_1.latest.json

      # Checks-out master without clean to keep the updated data-dictionary file
      - uses: actions/checkout@v2
        with:
          ref: main
          clean: 'false'
      
      # Running validation action
      - uses: ./github-actions/data-dictionary-checks/